model:
  name: 'Resshift'

resshift: 
  model:
    target: models.resshift.models.unet.UNetModelSwin
    ckpt_path: ~
    params:
      image_size: 128
      in_channels: 1
      model_channels: 160
      out_channels: 1
      attention_resolutions: [128,64,32,16]
      dropout: 0
      channel_mult: [1, 2, 2, 4]
      num_res_blocks: [2, 2, 2, 2]
      conv_resample: True
      dims: 2
      use_fp16: False
      num_head_channels: 32
      use_scale_shift_norm: True
      resblock_updown: False
      swin_depth: 2
      swin_embed_dim: 192
      window_size: 8
      mlp_ratio: 4
      cond_lq: True
      lq_size: 128

  diffusion:
    target: models.resshift.models.script_util.create_gaussian_diffusion
    params:
      sf: 4
      schedule_name: exponential
      schedule_kwargs:
        power: 0.3
      etas_end: 0.99
      steps: 15
      min_noise_level: 0.04
      kappa: 2.0
      weighted_mse: False
      predict_type: xstart
      timestep_respacing: ~
      scale_factor: 1.0
      normalize_input: False
      latent_flag: False


data:
  name: 'ERA5wind'
  data_path: "D:/tmp/ERA5wind_vo_128_128_subset_10000.npy"
  sample_factor: 4
  shape: [128, 128]
  train_batchsize: 8
  eval_batchsize: 8
  train_ratio: 0.8
  valid_ratio: 0.1
  test_ratio: 0.1
  subset: False
  subset_ratio: 0.1
  normalize: True
  normalizer_type: 'PGN'

train:
  random_seed: 42
  cuda: True
  device: 0
  epochs: 100
  patience: 10
  eval_freq: 5
  saving_best: True
  load_ckpt: False
  ckpt_path: ''
  saving_ckpt: True
  ckpt_freq: 5
  ckpt_max: 5
  distribute: False
  distribute_mode: 'DDP'
  device_ids: [0]

optimize:
  optimizer: 'AdamW'
  lr: 0.0001
  weight_decay: 0.001

schedule:
  scheduler: 'StepLR'
  step_size: 30
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: 'D:/tmp/DiffSR_logs/ERA5wind_resshift'
  wandb: False
  wandb_project: 'DiffSR-ResShift-ERA5wind'

beta_schedule:
  train:
    schedule: 'linear'
    n_timestep: 2000
    linear_start: 1e-4
    linear_end: 2e-2
  val:
    schedule: 'linear'
    n_timestep: 2000
    linear_start: 1e-4
    linear_end: 2e-2
